// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58OnXpX7XLIrk6DLhZTeQo0NBjmGYg_g',
    appId: '1:10256671228:web:89eec688a9260229711279',
    messagingSenderId: '10256671228',
    projectId: 'voyage-d027a',
    authDomain: 'voyage-d027a.firebaseapp.com',
    storageBucket: 'voyage-d027a.appspot.com',
    measurementId: 'G-2Y50FJCXKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSAJFkHXIhVbtxxCH_5rnItvNOUxW6O0',
    appId: '1:10256671228:android:e50c4468c0b86bbc711279',
    messagingSenderId: '10256671228',
    projectId: 'voyage-d027a',
    storageBucket: 'voyage-d027a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJerw_zBGVS9XdS1MN1i1h1cr4y4wp20',
    appId: '1:10256671228:ios:fd8b8efcae5d007b711279',
    messagingSenderId: '10256671228',
    projectId: 'voyage-d027a',
    storageBucket: 'voyage-d027a.appspot.com',
    iosClientId: '10256671228-3bjl779dkekvkctm3l2vei7s9bqf71bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJerw_zBGVS9XdS1MN1i1h1cr4y4wp20',
    appId: '1:10256671228:ios:fd8b8efcae5d007b711279',
    messagingSenderId: '10256671228',
    projectId: 'voyage-d027a',
    storageBucket: 'voyage-d027a.appspot.com',
    iosClientId: '10256671228-3bjl779dkekvkctm3l2vei7s9bqf71bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}
